// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzmiulrqukrglistgzhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bWl1bHJxdWtyZ2xpc3RnemhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTk5ODAsImV4cCI6MjA3MjA3NTk4MH0.D2UWFawbHfyPyVf6J7cas8wMB6c6IsX6IQykBwHP-AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});